package:
  name: r-hmisc
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "3.14_6"

source:
  fn: Hmisc_3.14-6.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/Hmisc_3.14-6.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/Hmisc/Hmisc_3.14-6.tar.gz
  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1 # [osx]

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: chron, rms, mice, tables
requirements:
  build:
    - r
    - r-formula
    - r-acepack
    - r-cluster # [not win]
    - r-foreign # [not win]
    - r-lattice # [not win]
    - r-latticeextra
    - r-nnet # [not win]
    - r-rpart # [not win]
    - r-survival >=2.37_6 # [not win]

  run:
    - r
    - r-formula
    - r-acepack
    - r-cluster # [not win]
    - r-foreign # [not win]
    - r-lattice # [not win]
    - r-latticeextra
    - r-nnet # [not win]
    - r-rpart # [not win]
    - r-survival >=2.37_6 # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('Hmisc')" # [not win]
    - "\"%R%\" -e \"library('Hmisc')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://biostat.mc.vanderbilt.edu/Hmisc, https://github.com/harrelfe/Hmisc
  license: GPL (>= 2)
  summary: The Hmisc package contains many functions useful for data analysis, high-level graphics,
    utility operations, functions for computing sample size and power, importing datasets,
    imputing missing values, advanced table making, variable clustering, character string
    manipulation, conversion of R objects to LaTeX code, and recoding variables.

# The original CRAN metadata for this package was:

# Package: Hmisc
# Version: 3.14-6
# Date: 2014-11-16
# Title: Harrell Miscellaneous
# Author: Frank E Harrell Jr <f.harrell@vanderbilt.edu>, with contributions from Charles Dupont and many others.
# Maintainer: Frank E Harrell Jr <f.harrell@vanderbilt.edu>
# Depends: methods, grid, lattice, survival (>= 2.37-6), Formula
# Imports: latticeExtra, cluster, rpart, nnet, acepack, foreign
# Suggests: chron, rms, mice, tables
# Description: The Hmisc package contains many functions useful for data analysis, high-level graphics, utility operations, functions for computing sample size and power, importing datasets, imputing missing values, advanced table making, variable clustering, character string manipulation, conversion of R objects to LaTeX code, and recoding variables.
# License: GPL (>= 2)
# LazyLoad: Yes
# URL: http://biostat.mc.vanderbilt.edu/Hmisc, https://github.com/harrelfe/Hmisc
# Packaged: 2014-11-21 18:05:11 UTC; harrelfe
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2014-11-22 00:42:24

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml