package:
  name: r-rex
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "0.2.0"

source:
  fn: rex_0.2.0.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/rex_0.2.0.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/rex/rex_0.2.0.tar.gz
  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1 # [osx]

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, knitr, dplyr, ggplot2
requirements:
  build:
    - r
    - r-lazyeval
    - r-magrittr

  run:
    - r
    - r-lazyeval
    - r-magrittr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rex')" # [not win]
    - "\"%R%\" -e \"library('rex')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/kevinushey/rex
  license: MIT + file LICENSE
  summary: A more friendly, human-readable interface for the construction of regular expressions.

# The original CRAN metadata for this package was:

# Package: rex
# Type: Package
# Title: Friendly Regular Expressions
# Version: 0.2.0
# Date: 2014-10-31
# Authors@R: as.person(c( "Kevin Ushey <kevinushey@gmail.com> [aut]", "Jim Hester <james.f.hester@gmail.com> [cre, aut]" ))
# Maintainer: Jim Hester <james.f.hester@gmail.com>
# URL: https://github.com/kevinushey/rex
# BugReports: https://github.com/kevinushey/rex/issues
# Description: A more friendly, human-readable interface for the construction of regular expressions.
# Imports: magrittr, lazyeval
# License: MIT + file LICENSE
# Suggests: testthat, knitr, dplyr, ggplot2
# VignetteBuilder: knitr
# Collate: 'aaa.R' 'utils.R' 'escape.R' 'capture.R' 'character_class.R' 'counts.R' 'lookarounds.R' 'match.R' 'or.R' 'rex-mode.R' 'rex.R' 'shortcuts.R' 'wildcards.R' 'zzz.R'
# Packaged: 2014-11-26 17:22:14 UTC; james.hester
# Author: Kevin Ushey [aut], Jim Hester [cre, aut]
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2014-11-26 18:49:27

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml