package:
  name: r-coda
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "0.16_1"

source:
  fn: coda_0.16-1.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/coda_0.16-1.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/coda/coda_0.16-1.tar.gz
  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1 # [osx]

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r >=2.14.0
    - r-lattice # [not win]

  run:
    - r >=2.14.0
    - r-lattice # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('coda')" # [not win]
    - "\"%R%\" -e \"library('coda')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  #home:
  license: GPL (>= 2)
  summary: Output analysis and diagnostics for Markov Chain Monte Carlo simulations.

# The original CRAN metadata for this package was:

# Package: coda
# Version: 0.16-1
# Date: 2012-11-06
# Title: Output analysis and diagnostics for MCMC
# Authors@R: c(person("Martyn", "Plummer", role=c("aut","cre","trl"), email="plummerm@iarc.fr"), person("Nicky", "Best", role="aut"), person("Kate", "Cowles", role="aut"), person("Karen", "Vines", role="aut"), person("Deepayan", "Sarkar", role="aut"), person("Russell", "Almond", role="ctb"))
# Depends: R (>= 2.14.0), lattice
# Description: Output analysis and diagnostics for Markov Chain Monte Carlo simulations.
# License: GPL (>= 2)
# Packaged: 2012-11-06 13:12:03 UTC; martyn
# Author: Martyn Plummer [aut, cre, trl], Nicky Best [aut], Kate Cowles [aut], Karen Vines [aut], Deepayan Sarkar [aut], Russell Almond [ctb]
# Maintainer: Martyn Plummer <plummerm@iarc.fr>
# Repository: CRAN
# Date/Publication: 2012-11-06 13:24:00
# NeedsCompilation: no

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml