package:
  name: r-vgam
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "0.9_6"

source:
  fn: VGAM_0.9-6.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/VGAM_0.9-6.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/VGAM/VGAM_0.9-6.tar.gz
  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1 # [osx]

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: VGAMdata, MASS
requirements:
  build:
    - r >=3.0.0

  run:
    - r >=3.0.0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('VGAM')" # [not win]
    - "\"%R%\" -e \"library('VGAM')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.stat.auckland.ac.nz/~yee/VGAM
  license: GPL-2
  summary: An implementation of about 6 major classes of statistical regression models. At the
    heart of it are the vector generalized linear and additive model (VGLM/VGAM) classes.  Many
    (150+) models and distributions are estimated by maximum likelihood estimation (MLE)
    or penalized MLE, using Fisher scoring. VGLMs can be loosely thought of as multivariate
    GLMs. VGAMs are data-driven VGLMs (i.e., with smoothing). The other classes are
    RR-VGLMs (reduced-rank VGLMs), quadratic RR-VGLMs, reduced-rank VGAMs, RCIMs (row-column
    interaction models)---these classes perform constrained and unconstrained quadratic
    ordination (CQO/UQO) models in ecology, as well as constrained additive ordination
    (CAO). Note that these functions are subject to change, especially before version
    1.0.0 is released; see the NEWS file for latest changes.

# The original CRAN metadata for this package was:

# Package: VGAM
# Version: 0.9-6
# Date: 2014-12-08
# Title: Vector Generalized Linear and Additive Models
# Author: Thomas W. Yee <t.yee@auckland.ac.nz>
# Maintainer: Thomas Yee <t.yee@auckland.ac.nz>
# Depends: R (>= 3.0.0), methods, stats, stats4, splines
# Suggests: VGAMdata, MASS
# Description: An implementation of about 6 major classes of statistical regression models. At the heart of it are the vector generalized linear and additive model (VGLM/VGAM) classes.  Many (150+) models and distributions are estimated by maximum likelihood estimation (MLE) or penalized MLE, using Fisher scoring. VGLMs can be loosely thought of as multivariate GLMs. VGAMs are data-driven VGLMs (i.e., with smoothing). The other classes are RR-VGLMs (reduced-rank VGLMs), quadratic RR-VGLMs, reduced-rank VGAMs, RCIMs (row-column interaction models)---these classes perform constrained and unconstrained quadratic ordination (CQO/UQO) models in ecology, as well as constrained additive ordination (CAO). Note that these functions are subject to change, especially before version 1.0.0 is released; see the NEWS file for latest changes.
# License: GPL-2
# URL: http://www.stat.auckland.ac.nz/~yee/VGAM
# NeedsCompilation: yes
# BuildVignettes: yes
# LazyLoad: yes
# LazyData: yes
# Packaged: 2014-12-08 03:56:18 UTC; tyee001
# Repository: CRAN
# Date/Publication: 2014-12-08 08:23:11

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml