package:
  name: swig
  version: 3.0.2

source:
  fn: swig-3.0.2.tar.gz
  url: http://prdownloads.sourceforge.net/swig/swig-3.0.2.tar.gz

build:
  detect_binary_files_with_prefix: True

requirements:
  build:
    - pcre
    - python
  run:
    - pcre

test:
  commands:
    - swig -help

about:
    home: http://www.swig.org/
    license: GPLv3
