package:
  name: fontconfig
  version: 2.11.1

source:
  fn: fontconfig-2.11.1.tar.bz2
  url: http://www.freedesktop.org/software/fontconfig/release/fontconfig-2.11.1.tar.bz2
  md5: 824d000eb737af6e16c826dd3b2d6c90
  patches:
    - fc-cache.patch [linux]

build:
  detect_binary_files_with_prefix: true
  number: 3

requirements:
  build:
    - freetype  >=2.5.2
    - libxml2
    - libpng
  run:
    - freetype  >=2.5.2
    - libxml2
    - libpng

about:
    home: http://www.freedesktop.org/wiki/Software/fontconfig/
    license: BSD
