package:
  name: r-sp
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.0_17"

source:
  fn: sp_1.0-17.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/sp_1.0-17.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/sp/sp_1.0-17.tar.gz
  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1 # [osx]

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: RColorBrewer, rgdal (>= 0.8-7), rgeos (>= 0.2-20), gstat
requirements:
  build:
    - r >=2.14.0
    - r-lattice # [not win]

  run:
    - r >=2.14.0
    - r-lattice # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('sp')" # [not win]
    - "\"%R%\" -e \"library('sp')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://r-forge.r-project.org/projects/rspatial/ http://rspatial.r-forge.r-project.org/
  license: GPL (>= 2)
  summary: A package that provides classes and methods for spatial data. The classes document
    where the spatial location information resides, for 2D or 3D data. Utility functions
    are provided, e.g. for plotting data as maps, spatial selection, as well as methods
    for retrieving coordinates, for subsetting, print, summary, etc.

# The original CRAN metadata for this package was:

# Package: sp
# Version: 1.0-17
# Date: 2014-11-16
# Title: classes and methods for spatial data
# Authors@R: c(person("Edzer", "Pebesma", role = c("aut", "cre"), email = "edzer.pebesma@uni-muenster.de"), person("Roger", "Bivand", role = "aut", email = "Roger.Bivand@nhh.no"), person("Barry", "Rowlingson", role = "ctb"), person("Virgilio", "Gomez-Rubio", role = "ctb"), person("Robert", "Hijmans", role = "ctb"))
# Depends: R (>= 2.14.0)
# Imports: methods, graphics, utils, lattice, grid
# Suggests: RColorBrewer, rgdal (>= 0.8-7), rgeos (>= 0.2-20), gstat
# Description: A package that provides classes and methods for spatial data. The classes document where the spatial location information resides, for 2D or 3D data. Utility functions are provided, e.g. for plotting data as maps, spatial selection, as well as methods for retrieving coordinates, for subsetting, print, summary, etc.
# License: GPL (>= 2)
# URL: https://r-forge.r-project.org/projects/rspatial/ http://rspatial.r-forge.r-project.org/
# Collate: bpy.colors.R AAA.R Class-CRS.R CRS-methods.R Class-Spatial.R Spatial-methods.R projected.R Class-SpatialPoints.R SpatialPoints-methods.R Class-SpatialPointsDataFrame.R SpatialPointsDataFrame-methods.R Class-GridTopology.R Class-SpatialGrid.R Class-SpatialGridDataFrame.R Class-SpatialLines.R SpatialLines-methods.R Class-SpatialLinesDataFrame.R SpatialLinesDataFrame-methods.R Class-SpatialPolygons.R Class-SpatialPolygonsDataFrame.R SpatialPolygons-methods.R SpatialPolygonsDataFrame-methods.R GridTopology-methods.R SpatialGrid-methods.R SpatialGridDataFrame-methods.R SpatialPolygons-internals.R point.in.polygon.R SpatialPolygons-displayMethods.R zerodist.R image.R stack.R bubble.R mapasp.R select.spatial.R gridded.R asciigrid.R spplot.R over.R overlay.R spsample.R recenter.R dms.R gridlines.R spdists.R rbind.R flipSGDF.R chfids.R loadmeuse.R compassRose.R surfaceArea.R spOptions.R subset.R disaggregate.R sp_spat1.R merge.R aggregate.R
# Packaged: 2015-01-07 20:23:35 UTC; edzer
# Author: Edzer Pebesma [aut, cre], Roger Bivand [aut], Barry Rowlingson [ctb], Virgilio Gomez-Rubio [ctb], Robert Hijmans [ctb]
# Maintainer: Edzer Pebesma <edzer.pebesma@uni-muenster.de>
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2015-01-08 11:01:50

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml