
package:
    name: selenium-chromedriver
    version: 2.12.0

source:
    fn: chromedriver_linux64.zip                                                        # [linux64]
    url: http://chromedriver.storage.googleapis.com/2.12/chromedriver_linux64.zip       # [linux64]
    md5: f306b93ff1b34af74371cee87d6560e4                                               # [linux64]
    fn: chromedriver_linux32.zip                                                        # [linux32]
    url: http://chromedriver.storage.googleapis.com/2.12/chromedriver_linux32.zip       # [linux32]
    md5: 6f4041e7f8300380cc2a13babbac354e                                               # [linux32]
    fn: chromedriver_win32.zip                                                          # [win32]
    url: http://chromedriver.storage.googleapis.com/2.12/chromedriver_win32.zip         # [win32]
    md5: 51eb47ad5ea91422aa1aaa400a724e7b                                               # [win32]

build:
    number: 0

test:
    commands:
        - chromedriver --help

about:
    home: https://code.google.com/p/selenium/wiki/ChromeDriver
    license: New BSD License

