package:
  name: buildbot-slave
  version: "0.8.10"

source:
  fn: buildbot-slave-0.8.10.tar.gz
  url: https://pypi.python.org/packages/source/b/buildbot-slave/buildbot-slave-0.8.10.tar.gz
  md5: da7b078f58b63076b2b312b573720283
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - buildbot-slave = buildbot-slave:main
    #
    # Would create an entry point called buildbot-slave that calls buildbot-slave.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - twisted >=8.0.0

  run:
    - python
    - twisted >=8.0.0

test:
  # Python imports
  imports:
    - buildslave
    - buildslave.commands
    - buildslave.monkeypatches
    - buildslave.scripts
    - buildslave.test
    - buildslave.test.fake
    - buildslave.test.unit
    - buildslave.test.util

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - mock

about:
  home: http://buildbot.net/
  license: GNU General Public License (GPL)
  summary: 'BuildBot Slave Daemon'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
