
package:
    name: nginx
    version: 1.4.3

source:
    fn: nginx-1.4.3.tar.gz
    url: http://nginx.org/download/nginx-1.4.3.tar.gz
    #md5:
   
    patches:
       - configure.patch

build:
    number: 5

requirements:
    build:
        - openssl
        - zlib
        - pcre

    run:
        - openssl
        - zlib
        - pcre 

about:
    home: http://www.nginx.org
    license: 2-clause BSD-like license

