package:
  name: r-rgl
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "0.95.1201"

source:
  fn: rgl_0.95.1201.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/rgl_0.95.1201.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/rgl/rgl_0.95.1201.tar.gz
  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1 # [osx]

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: MASS, knitr, rmarkdown
requirements:
  build:
    - r >=2.15.0

  run:
    - r >=2.15.0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rgl')" # [not win]
    - "\"%R%\" -e \"library('rgl')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://r-forge.r-project.org/projects/rgl/
  license: GPL
  summary: Provides medium to high level functions for 3D interactive graphics, including functions
    modelled on base graphics (plot3d(), etc.) as well as functions for  constructing
    representations of geometric objects (cube3d(), etc.).  Output may be on screen
    using OpenGL, or to various standard 3D file formats including  WebGL, PLY, OBJ,
    STL as well as 2D image formats, including PNG, Postscript, SVG, PGF.

# The original CRAN metadata for this package was:

# Package: rgl
# Version: 0.95.1201
# Title: 3D visualization device system (OpenGL)
# Author: Daniel Adler <dadler@uni-goettingen.de>, Duncan Murdoch <murdoch@stats.uwo.ca>, and others (see README)
# Maintainer: Duncan Murdoch <murdoch@stats.uwo.ca>
# Depends: R (>= 2.15.0),stats,grDevices
# Suggests: MASS, knitr, rmarkdown
# Description: Provides medium to high level functions for 3D interactive graphics, including functions modelled on base graphics (plot3d(), etc.) as well as functions for  constructing representations of geometric objects (cube3d(), etc.).  Output may be on screen using OpenGL, or to various standard 3D file formats including  WebGL, PLY, OBJ, STL as well as 2D image formats, including PNG, Postscript, SVG, PGF.
# License: GPL
# URL: https://r-forge.r-project.org/projects/rgl/
# SystemRequirements: OpenGL, GLU Library, zlib (optional), libpng (>=1.2.9, optional), FreeType (optional)
# BugReports: https://r-forge.r-project.org/projects/rgl/
# VignetteBuilder: knitr
# Packaged: 2014-12-21 16:23:41 UTC; murdoch
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2014-12-21 18:26:24

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml