package:
  name: r-plyr
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.8.1"

source:
  fn: plyr_1.8.1.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/plyr_1.8.1.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/plyr/plyr_1.8.1.tar.gz
  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1 # [osx]

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: abind, testthat, tcltk, foreach, doMC, itertools, iterators
requirements:
  build:
    - r >=2.11.0
    - r-rcpp >=0.11.0

  run:
    - r >=2.11.0
    - r-rcpp >=0.11.0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('plyr')" # [not win]
    - "\"%R%\" -e \"library('plyr')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://had.co.nz/plyr
  license: MIT + file LICENSE
  summary: 'plyr is a set of tools that solves a common set of problems: you need to break a
    big problem down into manageable pieces, operate on each pieces and then put all
    the pieces back together.  For example, you might want to fit a model to each spatial
    location or time point in your study, summarise data by panels or collapse high-dimensional
    arrays to simpler summary statistics. The development of plyr has been generously
    supported by BD (Becton Dickinson).'


# The original CRAN metadata for this package was:

# Package: plyr
# Type: Package
# Title: Tools for splitting, applying and combining data
# Version: 1.8.1
# Author: Hadley Wickham <h.wickham@gmail.com>
# Maintainer: Hadley Wickham <h.wickham@gmail.com>
# Description: plyr is a set of tools that solves a common set of problems: you need to break a big problem down into manageable pieces, operate on each pieces and then put all the pieces back together.  For example, you might want to fit a model to each spatial location or time point in your study, summarise data by panels or collapse high-dimensional arrays to simpler summary statistics. The development of plyr has been generously supported by BD (Becton Dickinson).
# URL: http://had.co.nz/plyr
# Depends: R (>= 2.11.0)
# Imports: Rcpp (>= 0.11.0)
# LinkingTo: Rcpp
# Suggests: abind, testthat, tcltk, foreach, doMC, itertools, iterators
# License: MIT + file LICENSE
# LazyData: true
# Packaged: 2014-02-26 16:06:36 UTC; hadley
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2014-02-26 17:25:17

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml